import { CompanyProfile } from "./types";

export const curatedCompanies: CompanyProfile[] = [
  {
    id: "zerodha",
    name: "Zerodha",
    logo: "Z",
    domain: "Fintech / Wealthtech",
    isFintech: true,
    hybridPolicy: "Remote-first or Hybrid flexible (Bangalore)",
    ctcRating: "Premium (Base + Massive Profit Sharing, easily beats 50LPA)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Legendary lean UI team. Highly complex real-time charting & canvas systems (Kite UI).",
    aiPractices: "Pragmatic AI tool integration, internal developer efficiency focus.",
    stockType: "Substantial bonuses & internal ESOP buybacks.",
    scaleMetrics: "12M+ active traders with incredibly high concurrent DAU/MAU.",
    managerType: "Pure engineering-led, mature leads with deep frontend empathy.",
    cultureRating: "Outstanding. Renowned for zero-pressure, sustainable growth culture.",
    wlbRating: "Exceptional. Strictly 9-to-6, no weekend pings, perfect for marriage & life.",
    fitScore: 98,
    fitSummary: "An absolute dream fit. Zerodha is the most stable Fintech in India, has pristine UI engineering values, pays exceptionally, and guarantees world-class work-life balance."
  },
  {
    id: "razorpay",
    name: "Razorpay",
    logo: "R",
    domain: "Fintech / Payments",
    isFintech: true,
    hybridPolicy: "Hybrid (2-3 days WFO, Bangalore)",
    ctcRating: "Highly competitive (Easily offers 45-60LPA for SDE3/Staff FE + ESOPs)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Dedicated UI Architects and Principal Engineers defining design systems and checkout UI.",
    aiPractices: "Deploying AI checkout assistance, transaction routing AI models.",
    stockType: "Highly liquid ESOP program with frequent buybacks.",
    scaleMetrics: "Processes payments for 8M+ businesses, extreme DAU/MAU.",
    managerType: "Mature frontend division with seasoned, UI-first engineering managers.",
    cultureRating: "Great. Certified 'Great Place to Work' with strong engineering-driven culture.",
    wlbRating: "Good stability. Matured and structured, avoiding early-stage chaos.",
    fitScore: 95,
    fitSummary: "Razorpay checkmarks almost every item: Fintech leader, structured SDE3 compensation, strong design/frontend architecture, solid ESOPs, and an established team culture."
  },
  {
    id: "phonepe",
    name: "PhonePe",
    logo: "P",
    domain: "Fintech / Consumer Tech",
    isFintech: true,
    hybridPolicy: "Hybrid (2-3 days WFO, Bangalore)",
    ctcRating: "Top-Tier (SDE3 package ranges from 55LPA to 75LPA base + ESOPs)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Strong Principal UI Engineers leading highly complex micro-frontends and super-app architectures.",
    aiPractices: "AI-based fraud detection, conversational voice payments, personalized feeds.",
    stockType: "Lucrative ESOP grants with high appreciation value.",
    scaleMetrics: "450M+ registered users, massive DAU (35M+ daily transaction volume).",
    managerType: "Mature, tech-heavy frontend leaders who have grown within PhonePe.",
    cultureRating: "Strong. Fast-paced, engineering-focused, highly collaborative.",
    wlbRating: "Moderate to Good. Highly demanding, but very structured and stable.",
    fitScore: 92,
    fitSummary: "While PhonePe's pace is high, the scale (450M+ users) and compensation are elite. If you move to Bangalore for this, the pay will more than justify the shift."
  },
  {
    id: "atlassian",
    name: "Atlassian",
    logo: "A",
    domain: "MNC / Enterprise SaaS",
    isFintech: false,
    hybridPolicy: "Hybrid or Work from Anywhere (flexible Bangalore R&D center)",
    ctcRating: "Premium (Base 50-65LPA + very high US-listed RSUs, beats 75LPA total)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Creators of Atlaskit design system. Strong, global frontend chapter with multiple Principal UIEs.",
    aiPractices: "Atlassian Intelligence fully integrated across Jira, Confluence, and Trello.",
    stockType: "Liquid US-listed RSUs (highly valuable & stable).",
    scaleMetrics: "Used by 250,000+ businesses globally with millions of DAU.",
    managerType: "Seasoned global engineering managers with strict focus on mental health & empathy.",
    cultureRating: "Exceptional. Constantly ranked as a top Great Place to Work worldwide.",
    wlbRating: "Exceptional. Strict emphasis on work-life balance, hybrid flexibility, absolute stability.",
    fitScore: 94,
    fitSummary: "If you are open to a non-Fintech MNC, Atlassian is top-tier. Exceptional WLB (great for wedding planning!), premier UI engineering discipline, and very high stock compensation."
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "M",
    domain: "MNC / Tech Giant",
    isFintech: false,
    hybridPolicy: "Hybrid (2 days WFO, Gurgaon/Noida/Bangalore)",
    ctcRating: "Excellent (Gurgaon/Noida allows matching 40LPA+ easily, high US RSUs)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Pioneers of TypeScript and Fluent UI. Strong cohort of Principal/Partner UI Architects.",
    aiPractices: "Global leader in AI via Copilot integrations across all products.",
    stockType: "Highly stable, liquid US-listed Microsoft RSUs.",
    scaleMetrics: "Billions of DAU across Office, Teams, and Azure portals.",
    managerType: "Highly mature managers, established career pathways, structured mentorship.",
    cultureRating: "Excellent. Highly inclusive, stable, and deeply supportive of personal milestones.",
    wlbRating: "Exceptional. Legendary WLB and job security, highly stable for the long term.",
    fitScore: 93,
    fitSummary: "Microsoft matches your desire for Gurgaon/Noida region stability, high pay, premium stock options (RSUs), world-class UI principal guidance, and legendary work-life balance."
  },
  {
    id: "grab",
    name: "Grab",
    logo: "G",
    domain: "MNC / Super-app & Fintech",
    isFintech: true,
    hybridPolicy: "Hybrid (3 days WFO, Bangalore R&D)",
    ctcRating: "Top-Tier MNC (Easily matches 50-65LPA base + Nasdaq RSUs)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Dedicated global Frontend chapter leading high-performance super-app React Native & Web frames.",
    aiPractices: "Highly integrated AI for localized rides, dynamic pricing, and GrabPay lending.",
    stockType: "Nasdaq-listed RSUs with standard vesting schedules.",
    scaleMetrics: "35M+ monthly active users, processing millions of transactions daily.",
    managerType: "Extremely structured, frontend-oriented managers with a global collaborative outlook.",
    cultureRating: "Excellent. Very stable, international-minded engineering standards.",
    wlbRating: "Good to Great. Structured work hours, highly respectful of personal time.",
    fitScore: 91,
    fitSummary: "Grab offers the perfect bridge of high-scale Fintech combined with structured MNC compensation and Nasdaq-listed RSUs, backed by highly disciplined frontend architectures."
  },
  {
    id: "groww",
    name: "Groww",
    logo: "Gr",
    domain: "Fintech / Investments",
    isFintech: true,
    hybridPolicy: "Hybrid (3 days WFO, Bangalore)",
    ctcRating: "Highly competitive (Offers 45-55LPA base for senior UI roles + ESOPs)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Highly complex stock charts, portfolios, and trading interfaces. Dedicated Frontend Architects.",
    aiPractices: "AI-powered stock suggestions, predictive investment insights, smart search.",
    stockType: "Wealthy ESOP packages for senior hires.",
    scaleMetrics: "30M+ users with very high DAU on trading days.",
    managerType: "FE dev teams led by seasoned tech managers with deep frontend architecture backgrounds.",
    cultureRating: "Good. Fast-growing Fintech culture with modern tech values.",
    wlbRating: "Good. Highly stable financial broker, matured beyond startup hustle.",
    fitScore: 90,
    fitSummary: "Groww is a mature investment leader with massive DAU/MAU. The frontend requires high-performance charting and complex dashboards, providing rich architectural challenges."
  },
  {
    id: "pinelabs",
    name: "Pine Labs",
    logo: "PL",
    domain: "Fintech / Merchant Merchant Tech",
    isFintech: true,
    hybridPolicy: "Hybrid (3 days WFO, Noida / Gurgaon)",
    ctcRating: "Very good (Gurgaon/Noida location alignment matches SDE3 40LPA+ easily)",
    hasUiPrincipals: true,
    uiPrincipalDetails: "Enterprise-grade UI platforms for merchant apps. Seasoned frontend leads in NCR.",
    aiPractices: "Merchant analytics, payment routing AI, smart terminal software.",
    stockType: "Pre-IPO ESOPs with high long-term value.",
    scaleMetrics: "Over 1M+ active merchant terminals, processing billions of transactions.",
    managerType: "Mature enterprise managers with solid background in enterprise frontend delivery.",
    cultureRating: "Good. Very professional, highly corporate, stable environment.",
    wlbRating: "Great. Very structured corporate hours, stable environment perfect for marriage.",
    fitScore: 89,
    fitSummary: "Pine Labs matches your direct desire for stable Fintech in the Gurgaon (GGN) / NCR area, letting you stay close to home with competitive pay, mature teams, and exceptional stability."
  }
];
